#!/usr/bin/env python3
"""
KG Update Executor
Executes KG update commands generated by LLM.
"""

from typing import Dict
from kg_storage import (
    add_food_node, update_food_node, add_interaction, get_or_create_zone
)


def execute_kg_update(
    kg: Dict,
    command: Dict,
    narration_info: Dict,
    verbose: bool = False
) -> bool:
    """
    Execute a KG update command.

    Args:
        kg: Knowledge graph
        command: Parsed update command from LLM
        narration_info: Original narration info
        verbose: Print detailed information

    Returns:
        True if successful
    """
    update_type = command['update_type']
    history_entry = command['history_entry']

    # Get or create location context zone
    location_context = None
    if narration_info.get('location_entity'):
        location_context = get_or_create_zone(
            kg,
            narration_info['location_entity'],
            "Storage"
        )
        history_entry['location_context'] = location_context

    if update_type == "CREATE_NEW":
        # Create new food node
        new_food_info = command.get('new_food_info', {})
        food_name = new_food_info.get('name') or narration_info.get('food_entity')

        # Validate food_name is not None
        if not food_name:
            print(f"  Error: Cannot create food node without a name")
            print(f"    new_food_info: {new_food_info}")
            print(f"    narration_info food_entity: {narration_info.get('food_entity')}")
            return False

        # Determine initial location from updates
        initial_location = None
        updates = command.get('updates', {})
        if 'location' in updates:
            if updates['location'] is None:
                # Food is in hand
                initial_location = None
            elif updates['location'].startswith('zone_'):
                # Already a zone_id
                initial_location = updates['location']
            else:
                # Convert location name to zone_id
                initial_location = get_or_create_zone(kg, updates['location'], "Storage")

        food_id = add_food_node(
            kg,
            name=food_name,
            state=new_food_info.get('state', 'unknown'),
            quantity=new_food_info.get('quantity', 'unknown'),
            location=initial_location,
            first_seen_time=narration_info['start_time']
        )

        if verbose:
            print(f"  ✓ Created new food: {food_id}")

    elif update_type == "UPDATE_EXISTING":
        # Update existing food node
        food_id = command['target_food_id']

        if food_id not in kg['foods']:
            print(f"  Error: Food ID {food_id} not found in KG")
            return False

        # Apply updates (if any)
        updates = command.get('updates', {})
        if updates:
            # Handle location update
            if 'location' in updates:
                if updates['location'] is None:
                    # Food is now in hand
                    updates['location'] = None
                elif updates['location'].startswith('zone_'):
                    # Already a zone_id
                    pass
                else:
                    # Convert location name to zone_id
                    updates['location'] = get_or_create_zone(kg, updates['location'], "Storage")

            update_food_node(kg, food_id, updates)

            if verbose:
                print(f"  ✓ Updated {food_id}: {updates}")

    else:
        print(f"  Error: Unknown update_type: {update_type}")
        return False

    # Always add interaction (for both CREATE_NEW and UPDATE_EXISTING)
    add_interaction(
        kg, food_id,
        history_entry['start_time'],
        history_entry['end_time'],
        history_entry['action'],
        history_entry['narration_text'],
        history_entry.get('location_context', ''),
        video_id=narration_info.get('video_id')
    )

    if verbose and update_type == "UPDATE_EXISTING":
        print(f"  ✓ Added interaction to {food_id}")

    return True
